export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as ServicesPage } from './ServicesPage'
export { default as ContactPage } from './ContactPage'
export { default as MvpPage } from './MvpPage'
export { default as MvpFormPage } from './MvpFormPage'
export { default as SignUpPage } from './SignUpPage'
